# Generated by Django 4.1.1 on 2024-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicecompany_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecompany',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ServiceCompany',
        ),
    ]
