# Generated by Django 4.1.1 on 2024-05-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_servicecompany_user_delete_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Полное название компании'),
        ),
    ]
