# Generated by Django 4.1.1 on 2024-04-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('engine_serial_number', models.CharField(max_length=100)),
                ('transmission_serial_number', models.CharField(max_length=100)),
                ('driving_axle_serial_number', models.CharField(max_length=100)),
                ('steering_axle_serial_number', models.CharField(max_length=100)),
                ('supply_contract_number', models.CharField(max_length=100)),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=100)),
                ('operation_address', models.CharField(max_length=200)),
                ('configuration', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('directory_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('date_performed', models.DateField()),
                ('hours_worked', models.IntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('performing_organization', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines_driving_axle', to='core.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines_engine', to='core.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines_model', to='core.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_companies',
            field=models.ManyToManyField(related_name='machines', to='core.servicecompany'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines_steering_axle', to='core.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines_transmission', to='core.reference'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('failure_node', models.CharField(max_length=100)),
                ('failure_description', models.TextField()),
                ('restoration_method', models.CharField(max_length=100)),
                ('spare_parts_used', models.TextField()),
                ('restoration_date', models.DateField()),
                ('downtime', models.IntegerField(editable=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.servicecompany')),
            ],
        ),
    ]
