# Generated by Django 4.1.1 on 2024-04-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_machine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
