# Generated by Django 4.1.1 on 2024-05-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicecompany_client'),
        ('core', '0004_machinebasicinfo_machineownershipinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.servicecompany'),
        ),
        migrations.AlterField(
            model_name='machinebasicinfo',
            name='driving_axle_model',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Модель ведущего моста'}, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_driving_axle_basic', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='machinebasicinfo',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Модель двигателя'}, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_engine_basic', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='machinebasicinfo',
            name='model',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Модель техники'}, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_model_basic', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='machinebasicinfo',
            name='steering_axle_model',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Модель управляемого моста'}, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_steering_axle_basic', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='machinebasicinfo',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Модель трансмиссии'}, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_transmission_basic', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='machineownershipinfo',
            name='service_companies',
            field=models.ManyToManyField(limit_choices_to={'directory_name': 'Сервисные компании'}, related_name='serviced_machines', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Вид ТО'}, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances_type', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='performing_organization',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Сервисные компании'}, on_delete=django.db.models.deletion.CASCADE, related_name='performing_organizations', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'directory_name': 'Сервисные компании'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to='core.reference'),
        ),
        migrations.DeleteModel(
            name='ServiceCompany',
        ),
    ]
