# Generated by Django 4.1.1 on 2024-05-06 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_claim_service_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'is_service_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='claims_service_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machineownershipinfo',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machineownershipinfo',
            name='service_companies',
            field=models.ManyToManyField(limit_choices_to={'is_service_company': True}, related_name='serviced_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'is_service_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
