# Generated by Django 4.1.1 on 2024-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_claim_service_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='self_maintained',
            field=models.BooleanField(default=False),
        ),
    ]
