# Generated by Django 4.1.1 on 2024-05-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenance_self_maintained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='service_company',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='service_company',
        ),
    ]
