# Generated by Django 4.1.1 on 2024-05-08 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_claim_service_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='performing_organization',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_service_company': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
