# Generated by Django 4.1.1 on 2024-05-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_maintenance_self_maintained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='failure_node',
            field=models.ForeignKey(blank=True, limit_choices_to={'directory_name': 'Узел отказа'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='claim_failure_nodes', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='restoration_method',
            field=models.ForeignKey(blank=True, limit_choices_to={'directory_name': 'Способ восстановления'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='claim_restoration_methods', to='core.reference'),
        ),
    ]
