# Generated by Django 4.1.1 on 2024-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_claim_failure_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='spare_parts_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
